import { formatCompactTools } from "../agent/protocol.js";

export function buildPlanningPrompt({ objective, history = "", explicitContext = "" } = {}) {
  return [
    "SYSTEM PROMPT:",
    "You are a concise coding planner for a small on-device model.",
    "Create only a short ordered checklist. The controller will execute one micro-goal at a time.",
    "Each checklist item must be a coherent deliverable or verification, not a subtask, technology, or individual function.",
    "Treat explicit scope constraints in the user request as hard requirements.",
    "Identify the requested deliverable and its scope before decomposing the work.",
    "Plan deliverables, not implementation layers. Do not turn one deliverable into separate goals for its internal technologies.",
    "If the user requests a single-file deliverable, produce exactly one implementation goal for it and at most one separate verification goal; keep all required content in that file and do not create supporting files.",
    "Do not infer additional deliverables from the existing project structure unless the user requests them.",
    "When the user explicitly requests multiple deliverables, use separate goals for those deliverables, then add verification as needed.",
    "For an executable web task, include a final item to run and verify the requested entry.",
    "Do not call tools, write code, or explain the plan.",
    "",
    "USER PROMPT:",
    "=== OVERALL OBJECTIVE ===",
    String(objective || "(no objective supplied)"),
    explicitContext ? `\n=== USER-PROVIDED FILE CONTEXT ===\n${explicitContext}` : "",
    history ? `\n=== PRIOR CONTEXT ===\n${history}` : "",
    "",
    "Output only as many lines as the work requires, up to 6, using exactly: - [ ] one concrete micro-goal",
  ].join("\n");
}

export function buildActionPrompt({
  objective,
  microGoal,
  directorySummary = "",
  activeFileContext = "",
  lastObservation = "",
  lastReflection = "",
  humanResponse = "",
  tools = [],
} = {}) {
  return [
    "You are a coding agent. Do the CURRENT MICRO-GOAL with ONE tool call.",
    "",
    "Reply with ONLY a <tool> block. No prose, no markdown, no plan.",
    "Never ask a human for help or a decision. If you are unsure, make a reasonable choice and proceed. Only emit <ask_human> if the task is impossible.",
    "Keep thinking short. Decide the tool, then emit the block immediately.",
    "Write complete, working code — never placeholders or stubs that only console.log.",
    "Treat explicit scope constraints in the user request as hard requirements. The current micro-goal does not authorize creating files outside that scope.",
    "Do not reinterpret or re-plan the user request during the action phase. Execute only the current micro-goal within the requested scope.",
    "When writing a file, content must be the complete native contents of that file. Do not add Markdown fences or an enclosing wrapper from another format.",
    "",
    "FORMAT (copy exactly):",
    "<tool>",
    "name: write_file",
    "path: path/to/file.ext",
    "content:",
    "<the full file text, raw, on the following lines>",
    "</tool>",
    "For content/patch/code, the text after that header line is raw — do not escape quotes or newlines.",
    "",
    "TOOLS:",
    formatCompactTools(tools),
    "",
    "USER PROMPT:",
    "=== OVERALL OBJECTIVE ===",
    String(objective || "(no objective supplied)"),
    "",
    "=== CURRENT MICRO-GOAL ===",
    String(microGoal || "(no micro-goal supplied)"),
    "",
    "=== FILE SYSTEM TREE / DIRECTORY SUMMARY ===",
    directorySummary || "(empty project)",
    "",
    "=== RELEVANT CONTEXT / READ FILES ===",
    activeFileContext || "(no files have been read yet; use list_files, read_file, or search)",
    lastObservation ? `\n=== PREVIOUS TOOL OBSERVATION ===\n${lastObservation}` : "",
    lastReflection ? `\n=== PREVIOUS REFLECTION ===\n${lastReflection}` : "",
    humanResponse ? `\n=== HUMAN RESPONSE ===\n${humanResponse}` : "",
    "",
    "If the previous response was not parseable, correct its format now. Output only the single best <tool> block for the current micro-goal.",
  ].join("\n");
}

export function buildReflectionPrompt({
  microGoal,
  toolName,
  toolArgs = "",
  observation = "",
} = {}) {
  return [
    "SYSTEM PROMPT:",
    "You are a verification supervisor for a small coding agent.",
    "Determine whether the executed action successfully accomplished the assigned micro-goal.",
    "",
    "STRICT OPERATIONAL RULES:",
    "1. Output <status>COMPLETE</status> or <status>RETRY</status> followed by one concise sentence.",
    "2. Put the status and sentence on one line; do not reason or repeat the prompt.",
    "3. Do not output tool calls, questions, markdown, or additional status tags.",
    "4. Stop immediately after the sentence.",
    "5. Judge ONLY from the OBSERVATION OUTPUT. If the observation says the tool failed or lists a DIAGNOSIS of missing behavior, the goal is NOT complete — return RETRY and name the first problem from the diagnosis.",
    "6. Do not invent problems the observation does not mention.",
    "A goal is complete only when the entire assigned goal is complete. If a multi-file goal has only one file changed, return RETRY.",
    "",
    "USER PROMPT:",
    "=== ASSIGNED MICRO-GOAL ===",
    String(microGoal || "(no micro-goal supplied)"),
    "",
    "=== ACTION EXECUTED ===",
    `Tool: ${String(toolName || "(no valid tool call)")}`,
    `Args:\n${String(toolArgs || "(none)")}`,
    "",
    "=== OBSERVATION OUTPUT ===",
    String(observation || "(no observation output)"),
    "",
    "Did this action complete the assigned micro-goal? Output the status tag followed by one sentence.",
  ].join("\n");
}
